### ISSUE TITLE
Run examples with errors.

### ISSUE THREAD

**Issue by linkerlin** [bwhite/hadoopy#74]
/usr/local/hadoopy/examples/l1-basic-with-hadoop/ex0-wordcount$ python driver.py 
WARNING:root:13/01/13 15:15:27 WARN streaming.StreamJob: -jobconf option is deprecated, please use -D instead.
Traceback (most recent call last):
  File "driver.py", line 21, in <module>
    word_counts = dict(hadoopy.readtb(output_path))
  File "/usr/local/lib/python2.7/dist-packages/hadoopy-0.6.0-py2.7-linux-i686.egg/hadoopy/_hdfs.py", line 341, in readtb
    yield tp_fp.next()
  File "_typedbytes.pyx", line 603, in _hadoopy_typedbytes.TypedBytesFile.__next__ (hadoopy/_typedbytes.c:4924)
  File "_typedbytes.pyx", line 515, in _hadoopy_typedbytes.__read_key_value_tb (hadoopy/_typedbytes.c:3713)
  File "_typedbytes.pyx", line 511, in _hadoopy_typedbytes._read_tb_code (hadoopy/_typedbytes.c:3670)
# IndexError: Bad index 47 

It's a strange thing.

**Comment by linkerlin** [comment]
I guess my hadoop cluster is broken. But the error message is misleading.
