### ISSUE TITLE
import sklearn in job crashes task

### ISSUE THREAD

**Issue by AlexanderKUA** [bwhite/hadoopy#84]
Hello,

I've found that just 'import sklearn' library in wc.py standard example generates such error:

```
Traceback (most recent call last):
  File "driver.py", line 15, in <module>
    hadoopy.launch(input_path, output_path, 'wc.py')
  File "/opt/anaconda/lib/python2.7/site-packages/hadoopy-0.6.0-py2.7-linux-            x86_64.egg/hadoopy/_runner.py", line 328, in launch
    raise subprocess.CalledProcessError(process.returncode, ' '.join(cmd))
subprocess.CalledProcessError: Command 'hadoop jar /usr/lib/hadoop-0.20-    mapreduce/contrib/streaming/hadoop-streaming.jar -output hadoopy-test-    data/1416578772.433620/wc-output -input hadoopy-test-data/1416578772.433620/wc-input -    mapper "python wc.py pipe map" -reducer "python wc.py pipe reduce" -combiner "python wc.py pipe     combine" -file wc.py -jobconf "mapred.job.name=wc" -io typedbytes -outputformat     org.apache.hadoop.mapred.SequenceFileOutputFormat -inputformat AutoInputFormat' returned     non-zero exit status 1
```

No matter we are using launch or launch_frozen. For example 'import of scipy' succeeds and no issues appears.

What might be a problem?

**Comment by nikhilketkar** [comment]
Need to look at the stderr logs. One way to get them is to go to the job tracker web page, identify the failed job, look that the failed attempts, click the last 4 Kb and copy paste it here.

**Comment by AlexanderKUA** [comment]
```
2014-11-21 08:30:00,232 INFO [IPC Server handler 1 on 50973]     org.apache.hadoop.mapred.TaskAttemptListenerImpl: JVM with ID:     jvm_1416576970157_0011_m_000003 given task: attempt_1416576970157_0011_m_000001_0
2014-11-21 08:30:00,671 INFO [IPC Server handler 3 on 50973]     org.apache.hadoop.mapred.TaskAttemptListenerImpl: Progress of TaskAttempt     attempt_1416576970157_0011_m_000000_0 is : 0.0
2014-11-21 08:30:00,680 FATAL [IPC Server handler 2 on 50973]     org.apache.hadoop.mapred.TaskAttemptListenerImpl: Task:     attempt_1416576970157_0011_m_000000_0 - exited : java.lang.RuntimeException:     PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

2014-11-21 08:30:00,680 INFO [IPC Server handler 2 on 50973]     org.apache.hadoop.mapred.TaskAttemptListenerImpl: Diagnostics report from     attempt_1416576970157_0011_m_000000_0: Error: java.lang.RuntimeException:     PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

2014-11-21 08:30:00,681 INFO [AsyncDispatcher event handler]     org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from     attempt_1416576970157_0011_m_000000_0: Error: java.lang.RuntimeException:     PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

2014-11-21 08:30:00,682 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl:     attempt_1416576970157_0011_m_000000_0 TaskAttempt Transitioned from RUNNING to     FAIL_CONTAINER_CLEANUP
2014-11-21 08:30:00,682 INFO [ContainerLauncher #2]     org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: Processing the event     EventType: CONTAINER_REMOTE_CLEANUP for container     container_1416576970157_0011_01_000002 taskAttempt     attempt_1416576970157_0011_m_000000_0
2014-11-21 08:30:00,683 INFO [ContainerLauncher #2]     org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: KILLING         attempt_1416576970157_0011_m_000000_0
```

**Comment by nikhilketkar** [comment]
These are the syslog logs. Need the stderr logs. Right next to where you copy pasted this from you will see a link saying "Last 4Kb"

If there is some confusion, consult the following to get the stderr logs

http://stackoverflow.com/questions/3207238/where-does-hadoop-mapreduce-framework-send-my-system-out-print-statements-s

This will contain the python stack trace indicating why this happened. I am guessing that scikits-learn is not installed on your compute nodes and the stderr will confirm that.

**Comment by AlexanderKUA** [comment]
The issue log is below:

```
Log Type: stderr
Log Length: 351
Traceback (most recent call last):
    File "wc.py", line 23, in <module>
    import sklearn
  File "/usr/lib64/python2.6/site-packages/sklearn/__init__.py", line 38, in <module>
    from .base import clone
  File "/usr/lib64/python2.6/site-packages/sklearn/base.py", line 10, in <module>
    from scipy import sparse
ImportError: No module named scipy
```

For some reason it searches in python2.6 for sklearn though I've specified Shebang line to 

```
#!/opt/anaconda/bin/python
```

for wc.py(original example)

This is anaconda sys.path output:

```
>>> sys.path
['/root/hadoopy/examples/l1-basic-with-hadoop/ex2-wordcount-writetb',     '/opt/anaconda/lib/python2.7/site-packages/hadoopy-0.6.0-py2.7-linux-x86_64.egg',     '/opt/anaconda/lib/python27.zip', '/opt/anaconda/lib/python2.7', '/opt/anaconda/lib/python2.7/plat-    linux2', '/opt/anaconda/lib/python2.7/lib-tk', '/opt/anaconda/lib/python2.7/lib-old',     '/opt/anaconda/lib/python2.7/lib-dynload', '/opt/anaconda/lib/python2.7/site-packages',     '/opt/anaconda/lib/python2.7/site-packages/PIL', '/opt/anaconda/lib/python2.7/site-packages/Sphinx-    1.2.3-py2.7.egg', '/opt/anaconda/lib/python2.7/site-packages/runipy-0.1.1-py2.7.egg',     '/opt/anaconda/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg']
```

Anyway thanks for help

**Comment by nikhilketkar** [comment]
You can use the "python_cmd" parameter in the "launch":

python_cmd – The python command to use. The default is “python”. Can be used to override the system default python, e.g. python_cmd = “python2.6”

http://hadoopy.readthedocs.org/en/latest/api.html?highlight=launch#hadoopy.launch

**Comment by AlexanderKUA** [comment]
I've uninstalled scikit-learn from python2.6 and still get an issue scikit-learn can't be found in job.

```
Log Type: stderr
Log Length: 371
Traceback (most recent call last):
  File "wc.py", line 36, in <module>
    import sklearn
ImportError: No module named sklearn
log4j:WARN No appenders could be found for logger     (org.apache.hadoop.metrics2.impl.MetricsSystemImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

But it can be found through normal python run.

I've added logging of Python environment inside job script:

```
python version:2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Aug 21 2014, 18:22:21)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.path:['/root/hadoopy/examples/l1-basic-with-hadoop/ex2-wordcount-writetb',     '/opt/anaconda/lib/python2.7/site-packages/hadoopy-0.6.0-py2.7-linux-x86_64.egg',     '/opt/anaconda/lib/python27.zip', '/opt/anaconda/lib/python2.7', '/opt/anaconda/lib/python2.7/plat-    linux2', '/opt/anaconda/lib/python2.7/lib-tk', '/opt/anaconda/lib/python2.7/lib-old',     '/opt/anaconda/lib/python2.7/lib-dynload', '/opt/anaconda/lib/python2.7/site-packages/runipy-0.1.1-    py2.7.egg', '/opt/anaconda/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg',     '/opt/anaconda/lib/python2.7/site-packages', '/opt/anaconda/lib/python2.7/site-packages/PIL',     '/opt/anaconda/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg']
installed packages
['abstract-rendering==0.5.1', 'argcomplete==0.8.1', 'astropy==0.4.2', 'atom==0.3.9', 'backports.ssl-    match-hostname==3.4.0.2', 'beautifulsoup4==4.3.2', 'binstar==0.7.1', 'bitarray==0.8.1',     'blaze==0.6.3', 'blz==0.6.2', 'bokeh==0.6.1', 'boto==2.32.1', 'casuarius==1.1', 'cdecimal==2.3',     'cffi==0.8.6', 'chaco==4.4.1', 'colorama==0.3.1', 'conda-build==1.8.2', 'conda==3.7.0',     'configobj==5.0.6', 'cryptography==0.5.4', 'cython==0.21.1', 'cytoolz==0.7.0', 'datashape==0.3.0',     'decorator==3.4.0', 'docutils==0.12', 'enable==4.3.0', 'enaml==0.9.8', 'flask==0.10.1',     'future==0.13.1', 'futures==2.1.6', 'gevent-websocket==0.9.3', 'gevent==1.0.1', 'greenlet==0.4.4',     'grin==1.2.1', 'h5py==2.3.1', 'hadoopy==0.6.0', 'ipython==2.2.0', 'itsdangerous==0.24', 'jdcal==1.0',     'jinja2==2.7.3', 'kiwisolver==0.1.3', 'llvmpy==0.12.7', 'lxml==3.4.0', 'markupsafe==0.23',     'matplotlib==1.4.0', 'mock==1.0.1', 'mpi4py==1.3', 'mrjob==0.4.2', 'multipledispatch==0.4.7',     'networkx==1.9.1', 'nltk==3.0.0', 'nose==1.3.4', 'numba==0.14.0', 'numexpr==2.3.1', 'numpy==1.9.0',     'openpyxl==1.8.5', 'pandas==0.14.1', 'patsy==0.3.0', 'pep8==1.5.7', 'pil==1.1.7', 'ply==3.4',     'psutil==2.1.1', 'py==1.4.25', 'pycosat==0.6.1', 'pycparser==2.10', 'pycrypto==2.6.1', 'pycurl==7.19.5',     'pyface==4.4.0', 'pyflakes==0.8.1', 'pygments==1.6', 'pyinstaller==2.1', 'pyopenssl==0.14',     'pyparsing==2.0.1', 'pytest==2.6.3', 'python-dateutil==1.5', 'pytz==2014.7', 'pyyaml==3.11',     'pyzmq==14.3.1', 'redis==2.9.1', 'requests==2.4.1', 'rope==0.9.4', 'runipy==0.1.1', 'scikit-    image==0.10.1', 'scikit-learn==0.15.2', 'scipy==0.14.0', 'simplejson==3.6.5', 'six==1.8.0', 'sockjs-    tornado==1.0.1', 'sphinx==1.2.3', 'spyder==2.3.1', 'sqlalchemy==0.9.7', 'statsmodels==0.5.0',     'sympy==0.7.5', 'tables==3.1.1', 'theano==0.6.0', 'toolz==0.7.0', 'tornado==4.0.2', 'traits==4.4.0',     'traitsui==4.4.0', 'ujson==1.33', 'unicodecsv==0.9.4', 'werkzeug==0.9.6', 'wsgiref==0.1.2',     'xlrd==0.9.3', 'xlsxwriter==0.5.7', 'xlwt==0.7.5']
```

What might be the reason of such issue?

**Comment by AlexanderKUA** [comment]
> > You can use the "python_cmd" parameter in the "launch"

Thanks. It works now.
Looks a bit strange because I've already set proper python to use through

```
#!/opt/anaconda/bin/python
```

in Hadoop script
